# \u7AEF\u53E3
server:
  port: 8011

spring:
  application:
    # \u670D\u52A1\u540D\u79F0
    name: user-service
  cloud:
    # nacos \u914D\u7F6E
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848